---
version: 2
updates:
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      # Check for updates to GitHub Actions every week
      interval: 'weekly'
  - package-ecosystem: 'docker-compose'
    directory: '/'
    schedule:
      interval: 'weekly'
    ignore:
      - dependency-name: 'elasticsearch'
        update-types: 'version-update:semver-major'
