language: perl
perl:
  - "5.18"
  - "5.16"
  - "5.14"
  - "5.12"
  - "5.10"

matrix:
  allow_failures:
    # As of 2013-11-02 there are a lot of dependencies
    # that still fail their own test suites on 5.18.
    - perl: "5.18"

notifications:
  email:
    recipients:
      - olaf@wundersolutions.com
    on_success: always
    on_failure: always
  irc: "irc.perl.org#metacpan-travis"


env:
  global:
    # We use a non-standard port to avoid trashing production
    # but travis will have it running on the standard port.
    - METACPAN_ES_TEST_PORT=9200


before_install:
  # We need to run a pre-1.0 instance of ES until we update everything.
  - wget https://download.elasticsearch.org/elasticsearch/elasticsearch/elasticsearch-0.90.13.deb
  - sudo dpkg -i elasticsearch-0.90.13.deb
  - sudo service elasticsearch restart

  - cpanm -n Devel::Cover::Report::Coveralls
  - cpanm Carton

install:
  - carton install


before_script:
  # Show status info for ES to verify that it's working, what version, etc.
  - "curl http://localhost:${METACPAN_ES_TEST_PORT}/"
  - "perl -i -pe 's/(servers :)9900/$1$ENV{METACPAN_ES_TEST_PORT}/' metacpan_server_testing.conf"

script:
  # Devel::Cover isn't in the cpanfile
  # but if it's installed into the global dirs this should work.
  # NOTE: No '-r' for prove; 't/fakecpan.t' does the recursion for us.
  - HARNESS_PERL_SWITCHES=-MDevel::Cover=+ignore,local carton exec prove -lv t

after_success:
  - cover -report coveralls


services:
  - elasticsearch
